server:
  port: 8000

zuul:
  ignoredServices: '*'
  prefix: /api
  routes:
    auth:
      path: /oauth/**
      serviceId: auth-service
      strip-prefix: false
      sensitiveHeaders: Cookie,Set-Cookie
    guesstheverbs:
      path: /verbs/**
      serviceId: guesstheverb
      strip-prefix: false
      sensitiveHeaders: Cookie,Set-Cookie
    answers:
      path: /answers/**
      serviceId: guesstheverb
      strip-prefix: false
    leaders:
      path: /leaders/**
      serviceId: gamification
      strip-prefix: false
    stats:
      path: /stats/**
      serviceId: gamification
      strip-prefix: false

---
spring:
  profiles: dev
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

---
spring:
  profiles: docker
eureka:
  client:
    serviceUrl:
      defaultZone: http://service-registry:8761/eureka/