server:
  port: 8000

zuul:
  ignoredServices: '*'
  prefix: /api
  routes:
    guesstheverbs:
      path: /verbs/**
      serviceId: guesstheverb
      strip-prefix: false
    answers:
      path: /answers/**
      serviceId: guesstheverb
      strip-prefix: false
    leaders:
      path: /leaders/**
      serviceId: gamification
      strip-prefix: false
    stats:
      path: /stats/**
      serviceId: gamification
      strip-prefix: false

#set /trace endpoint as not sensitive (not requiring authentication)
endpoints:
  routes:
    sensitive: false
  trace:
    sensitive: false

#ribbon:
#  eureka:
#    enabled: false

---
spring:
  profiles: dev
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

---
spring:
  profiles: docker
eureka:
  client:
    serviceUrl:
      defaultZone: http://service-registry:8761/eureka/